---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pihole
  namespace: network
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
spec:
  releaseName: pihole
  rollback:
    enable: true
  chart:
    repository: https://mojo2600.github.io/pihole-kubernetes/
    name: pihole
    version: 1.7.20
  values:
    DNS1: "1.1.1.1"
    DNS2: "8.8.8.8"
    replicaCount: 1
    persistentVolumeClaim:
        enabled: true
        storageClass: openebs-jiva-default
    extraEnvVars:
        CONDITIONAL_FORWARDING: 'True'
        CONDITIONAL_FORWARDING_IP: "192.168.178.1"
        CONDITIONAL_FORWARDING_DOMAIN: "fritz.box"
        CONDITIONAL_FORWARDING_REVERSE: "178.168.192.in-addr.arpa"
    serviceTCP:
        type: LoadBalancer
        loadBalancerIP: 192.168.178.254
        annotations:
          metallb.universe.tf/allow-shared-ip: pihole-svc
    serviceUDP:
        type: LoadBalancer
        loadBalancerIP: 192.168.178.254
        annotations:
          metallb.universe.tf/allow-shared-ip: pihole-svc