---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: k8s-at-home
  namespace: default
spec:
  # The interval at wich to check the upstream for updates
  interval: 24h
  # The repository URL, a valid URL contains at least a protocol and host
  url: https://k8s-at-home.com/charts/