---
apiVersion: helm.toolkit.fluxcd.io/v2beta1 
kind: HelmRelease
metadata:
  name: unifi
  namespace: network
spec:
  interval: 24h
  chart:
    spec:
      releaseName: unifi
      rollback:
        enable: true
      chart: unifi
      version: 2.0.4
      sourceRef:
        name: k8s-at-home
        namespace: default
      values:
        guiService:
          type: LoadBalancer
          loadBalancerIP: 192.168.178.253
          annotations:
            metallb.universe.tf/allow-shared-ip: unifi-svc
        controllerService:
          type: LoadBalancer
          loadBalancerIP: 192.168.178.253
          annotations:
            metallb.universe.tf/allow-shared-ip: unifi-svc
        stunService:
          type: LoadBalancer
          loadBalancerIP: 192.168.178.253
          annotations:
            metallb.universe.tf/allow-shared-ip: unifi-svc
        discoveryService:
          type: LoadBalancer
          loadBalancerIP: 192.168.178.253
          annotations:
            metallb.universe.tf/allow-shared-ip: unifi-svc
        persistence:
          storageClass:  openebs-hostpath 