---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: unifi
  namespace: network
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
spec:
  releaseName: unifi
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: unifi
    version: 1.0.0
  values:
    image:
      tag: 5.14.23
    guiService:
      type: LoadBalancer
      loadBalancerIP: 192.168.178.253
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi-svc
    controllerService:
      type: LoadBalancer
      loadBalancerIP: 192.168.178.253
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi-svc
    stunService:
      type: LoadBalancer
      loadBalancerIP: 192.168.178.253
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi-svc
    discoveryService:
      type: LoadBalancer
      loadBalancerIP: 192.168.178.253
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi-svc
    persistence:
      storageClass: openebs-jiva-default