---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: flux
  chart:
    repository: https://charts.fluxcd.io/
    name: flux
    version: 1.6.1
  values:
    helmOperator:
      create: false
    git:
      url: "git@github.com:moritz31/homelab-gitops"
      branch: master
      path: namespaces,deployments
    image:
      repository: raspbernetes/flux
      tag: 1.21.0
    registry:
      rps: 1
      burst: 1
    memcached:
      enabled: true
    syncGarbageCollection:
      enabled: true
      dry: false
    # Enabled once prometheus-operator is installed
    prometheus:
      enabled: true
      serviceMonitor:
        create: true
        interval: 30s
        scrapeTimeout: 10s
        namespace: flux
    dashboards:
      # If enabled, flux will create a configmap with a dashboard in json that's going to be picked up by grafana
      # See https://github.com/helm/charts/tree/master/stable/grafana#configuration - `sidecar.dashboards.enabled`
      enabled: true
      # The namespace where the dashboard is deployed, defaults to the installation namespace
      namespace:
      # The prefix of the generated configmaps
      nameprefix: dashboard