---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: openebs
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
spec:
  releaseName: openebs
  helmVersion: v3
  chart:
    repository: https://openebs.github.io/charts
    name: openebs
    version: 2.6.0
