---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
spec:
  releaseName: loki-stack
  rollback:
    enable: true
  chart:
    repository: https://grafana.github.io/helm-charts
    name: loki-stack
    version: 2.3.0
    values:
      grafana:
        enabled: true