---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
spec:
  releaseName: kube-prometheus-stack
  rollback:
    enable: true
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: 13.5.0
  values:
    defaultRules:
    rules:
      kubeControllerManager:
        enabled: false
      kubeScheduler:
        enabled: false
    prometheus:
      ingress:
        enabled: true
        hosts:
          - "prometheus.fritz.box"
    alertmanager:
      ingress:
        enabled: true
        hosts:
          - "alertmanager.fritz.box"
      config:
        receivers:
          - name: 'null'
            webhook_configs:
            - url: http://10.0.0.1:9999
              send_resolved: true
    grafana:
      ingress:
        enabled: true
        hosts:
          - "grafana.fritz.box"
      sidecar:
        dashboards:
          enabled: true
    kube-state-metrics:
      image:
        repository: eddiezane/kube-state-metrics
        tag: v1.9.7