---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
spec:
  releaseName: kube-prometheus-stack
  rollback:
    enable: true
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: 12.2.4
  values:
    kube-state-metrics:
      image:
        repository: k8s.gcr.io/kube-state-metrics-arm64
        tag: v1.9.5